### ISSUE TITLE
MSX directories (MSX, MSX2, and MSX2+)

### ISSUE THREAD

**Issue by Sebbeug** [recalbox/recalbox-os#1000]
Think it's possible with last version of recalbox to use only one MSX directory. (actually 3 => /msx, /msx2 and /msx2+)
Default emulator is now Bluemsx, and all roms are usable from an unique directory.
/msx is enough

**Comment by rockaddicted** [comment]
Hello, yes indeed, only one msx directory could be enough. But people that want to separate the different MSX generations can no more do it.
So we'll let the different directories, and if you don't want to split your roms, you can use only msx folder.

**Comment by Sebbeug** [comment]
Yes... But it's a non-sens :
1- On a MSX2+, you can play with MSX2 and MSX games (MSX standard was backward compatible)
2- Can you give me only 1 MSX2+ title you can use with BlueMsx.libretro (.rom) ?
Answer is : No

So if we consider /msx2+ directory is useless...     /msx2 too ;)

**Comment by paradadf** [comment]
There are three folders.
- People that want to put all their MSX roms in one place, they use the folder called **msx** and become a logo with MS X 1-2-2+
- People that want to separate (regardless of its backward compatibility) MSX1 and MSX2 because they just prefer it would be using the folders **msx1** and **msx2**.

There were versions re-released for the MSX2 that aren't compatible with the less powerful MSX1 computers, so people just have the option to separate them if they want.

**Comment by Sebbeug** [comment]
I know this... i'm an old msx user ;)
But some people doesn't understand why, and it's not so simple with lot of directories...

**Comment by paradadf** [comment]
Your title says (MSX, MSX2 and MSX2+)... Correct would be (MSX, MSX1 and MSX2).
Anyway I haven't read a single person asking about it, so I don't know where you know that some people doesn't understand why those directories. And a little research here and rhe forum and you would understand what is it for.

**Comment by Sebbeug** [comment]
If i could see you on #recalbox IRC channel, you could understand.
I've done a package for MSX (scrap, gamelist, etc.), and some people asked to me where was the good place to drop roms, so don't be so sure of yourself pls.

I close this ticket, my only wish was to simplify the use of recalbox.
