### ISSUE TITLE
[4.1][Odroid XU4] N64 doesn't work

### ISSUE THREAD

**Issue by nosfay** [recalbox/recalbox-os#1006]
### What happened
Back to menu when I launch N64 games. I tried all core.
Im using same USB key for rpi3 and xu4.

### What should have happened
Launch game.

### Enumerate your devices
Odroid XU4

### How to reproduce the bug
Launch a game from ES.

**Comment by nadenislamarre** [comment]
you cant use the same usb key. the usb key conttains parametrrs specific to
rpi3 and xu4.
we could do a subfolder by arch and share roms but it doesnt exist for the
moment

**Comment by nosfay** [comment]
OK!

It's strange because all other emulators work (PSX, nes, dreamcast, gba).

**Comment by nadenislamarre** [comment]
Yes, that's true.
In fact only 2 things differs in the config files between xu4 and rpi3 (as far as i remember) :
- the n64 resolution (file recalbox.conf)
- the kodi cec configuration (file .kodi/user_data/something/something.xml)

but for example, for the x86, some other parameter will change (retroarch.cfg for example)

Note that there are more changes between the rpi1 and the rpi3 than between xu4 and rpi3 ;-)
If you plug your usb on a rpi 1, i guess that most of emulators will not work while the configuration is done for emulators not compiled on the rpi 1 (because it is not powerfull enough).

**Comment by nosfay** [comment]
I think I understand. 

This paramater n64.videomode=DMT 9 HDMI is dedicated to raspberry, so should I find the odroid equivalent ?

**Comment by nadenislamarre** [comment]
it's not dedicated to raspeberry, but it doesn't work on the xu4.

you can compare these 2 files:
https://github.com/recalbox/recalbox-buildroot/blob/rb-4.1.X/package/recalbox-system/rpi3/recalbox.conf
https://github.com/recalbox/recalbox-buildroot/tree/rb-4.1.X/package/recalbox-system/xu4

you've to change to n64.core=glide64mk2 on the xu4 while the others are specific to rpi.
and to global.videomode=CEA 1 HDMI

**Comment by nosfay** [comment]
I close the issue (it wasn't really one :p ) , thank you for the help
