### ISSUE TITLE
[4.0.0-Beta5][Moonlight] No keyboard + Mouse +/- Controller when streaming

### ISSUE THREAD

**Issue by myles786** [recalbox/recalbox-os#1052]
First off I must say that I love the concept and layout of Recalbox.

The problems are related to moonlight. I managed to install and start it without any major issues.
I had to enable xboxdrv in recalbox.conf to stop the controller light from flashing the whole time.
controllers.xboxdrv.enabled=1

**Problem 1**: When starting a game I cannot use the keyboard or mouse in-game that is attached to the Pi3. The keyboard and mouse attached to the source PC works fine though.

**Problem 2**: When streaming certain games I cannot use the Xbox 360 wireless controller attached to the Pi.

**Comment by substring** [comment]
I'd rather you use the forum to ask questions rather than submitting an issue :)

for problem 1, check https://github.com/recalbox/recalbox-configgen/issues/41
for problem 2, if you say certain games and not all games, that's a streaming problem.NVidia's gamestream are not 100% compatible with PC games
