### ISSUE TITLE
[4.0.0-beta5] Wifi setup still does not work

### ISSUE THREAD

**Issue by fullskull** [recalbox/recalbox-os#1058]

**Comment by paradadf** [comment]
@fullskull If you'll be providing zero new information, you might just close this issue.
https://github.com/recalbox/recalbox-os/issues/788

I told you [on the forum](https://forum.recalbox.com/topic/3576/no-consigo-wifi/20) to give more information that just "the wifi isn't working", but still nothing. Right now, your issue is merely an support question, an this isn't the place for that. I also told you to try with a different access point, but nothing as well.
