### ISSUE TITLE
Can't install recallbox on Raspi 0W

### ISSUE THREAD

**Issue by marcino239** [recalbox/recalbox-os#1251]
Version:
- recalboxOS 4.0.1
- recalboxOS 4.0.0

What happend:
- noobs install screen has all buttons grayed and no install screen is showing up for recallbox.  All is good with same SD card on raspi 3

**Comment by Laddyacris** [comment]
Hello
it's not compatible with theses versions of recalbox.

**Comment by amilanesi67** [comment]
With Recalbox 4.1?
Zero W is fundamental for handheld devices...

**Comment by Laddyacris** [comment]
With recalbox 4.1 you need few files. It's not possible now, it's not merged.

**Comment by kryptalivian** [comment]
you need to 

1. download https://downloads.raspberrypi.org/NOOBS_lite_latest 
2. latest recalbox download. 
3.Unzip both of them, 
4. On recalbox download - open the OS folder and copy/move the RPi1 folder over to the noobslite OS folder
5. Copy over all the files from noobs lite download and you will be ready to boot.

Otherwise here is a pre-done copy i did https://drive.google.com/open?id=0Bz2C40k1vIXVSERLU0ZOU0JOZGc

**Comment by kryptalivian** [comment]
fyi I haven't tried wifi or bluetooth. I just use my ps4  official sony ps4 dongle with my controller, not on board bluetooth.

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
