### ISSUE TITLE
[4.1][Recalbox Manager] Timezone not working

### ISSUE THREAD

**Issue by azvarel** [recalbox/recalbox-os#1264]
### What happened
Even modifying the timezone in the recalbox manager, restarting the rpi, the system continues with the native timezone Europe/Paris

In recalbox.conf I also took the ; that came in front of system.timezone=Europe/Paris and I put system.timezone=America/Recife and not working

### What should have happened
Should change the timezone to what the user has changed

### Enumerate your devices
RPI3

### How to reproduce the bug
Change via recalbox manager, or via recalbox.conf the timezone to another any ex. America / Recife, save, restart the recalbox.
When opening the emulator (hotkey + B) you can check the hour that are Europe / Paris
or
In SSH you can type `cat /etc/timezone`

### I solved this way
I edited the /etc/timezone Putting the region America/Recife. I saved
then I exported timezone type `export TZ=America/Recife`

Is Work!

**Comment by substring** [comment]
@djlechuck ?

**Comment by DjLeChuck** [comment]
@substring It's not related to the manager but with recalbox itself :)

**Comment by substring** [comment]
@azvarel holy crap, of course it can't work, i test a fix a report back with a test build

**Comment by substring** [comment]
@azvarel please test setting `updates.tpye=gitlab/82-can-t-set-timezone` in `recalbox.conf`. Still, i think the upgrade will fail because tar will have to replace an existing file with a symlink. If so, juste remove /etc/timezone and /etc/localtime and rerun the update.

Once tested and confirm, you can switch back to the normal unstable (and eventually redelete the 2 files before updating)

**Comment by azvarel** [comment]
NO UPDATES AVALIABLE

**Comment by azvarel** [comment]
Now working!

**Comment by substring** [comment]
solved with https://github.com/recalbox/recalbox-os/releases/tag/4.1.0
