### ISSUE TITLE
How to connect to wifi without a password?

### ISSUE THREAD

**Issue by njamessultana** [recalbox/recalbox-os#1275]
Im not sure how to connect to an unsecured wifi network. Im not sure what to put in the wifi key box or just leave it empty, because it hasnt been working leaving the box empty

**Comment by kryptto** [comment]
You cant use open unsecure wireless, this forum is for bugs, please use the recalbox main forum for questions.  Thanks!  ;)

Kryptto

On Jun 27, 2017 6:14 PM, njamessultana <notifications@github.com> wrote:

Im not sure how to connect to an unsecured wifi network. Im not sure what to put in the wifi key box or just leave it empty, because it hasnt been working leaving the box empty
