### ISSUE TITLE
Allow core to set automatic ratio.

### ISSUE THREAD

**Issue by digitalLumberjack** [recalbox/recalbox-os#201]

**Comment by Thekronics** [comment]
Since the last update in V3.3.0b3, there is a bug with the backup when trying to switch to a custom ratio. Indeed once the custom ratio is set, when leaving Retroarch and launch a new rom, it automatically switches to the standard ratio of Retroarch (and that while "save configuration on exit" is well selected).

Note that this anomaly is present only since the last update (third). The first two updates do not show the anomaly and well Retroarch retains the last saved ratio.

Note also, for the first two updates, the option "Games Size" of the interface need not be positioned Custom to the Custom ratio is stored under Retroarch.

**Comment by rockaddicted** [comment]
The problem about the preset "custom ratio" is not solved.
When the option is defined, configgen overwrite the custom ratio ratio preset when you boot a game instead of using the custom value defined in retroarch.cfg

**Comment by digitalLumberjack** [comment]
I'll take care of that this weekend

**Comment by Thekronics** [comment]
Hello DigitalLumberjack,

 

la beta 12 inclut elle déjà la correction ?

 

@ bientôt ! ^^

 

  _____  

De : digitalLumberjack [mailto:notifications@github.com] 
Envoyé : vendredi 30 octobre 2015 11:06
À : digitalLumberjack/recalbox-os
Cc : Thekronics
Objet : Re: [recalbox-os] Allow core to set automatic ratio. (#201)

 

I'll take care of that this weekend


Reply to this email directly or view
<https://github.com/digitalLumberjack/recalbox-os/issues/201#issuecomment-15
2479785>  it on GitHub.
<https://github.com/notifications/beacon/ANaIyWvOY6AAkpVTf7hz-Yxq13a43_Nnks5
pAzh-gaJpZM4D1DP9.gif>

**Comment by digitalLumberjack** [comment]
nope
