### ISSUE TITLE
cannot use 4 controllers

### ISSUE THREAD

**Issue by Mojo4242** [recalbox/recalbox-os#287]
Hi,

I have 4 connected and well configured controllers.
When launching a game (snes or playstation) all controllers names appears on the bottom of the screen but only the two first controllers are detected by the game.

**Comment by Laddyacris** [comment]
Hello
unfortunately it seems that PSX multitap is not supported at the moment
but for SNES, these is a solution.

Edit recalbox.conf
choose emulator snes9x  instead of pocketsnes
snes_emulator=snes9x

Save file

Edit /recalbox/configs/retroarch/retroarchcustom.cfg 

add : input_libretro_device_p2 =  "257"

Launch snes game, hotkey+Button B for rgui
Setting > General Setting > Configuration Save On Exit : ON
Setting > Input Setting > User 2 Device Type > Multitap 
> quit retroarch
reload game and test.

**Comment by digitalLumberjack** [comment]
Could it be default or does it works only with multitap games ?

**Comment by Mojo4242** [comment]
Hi @Laddyacris, thanks for you help.

In Setting > Input Setting > User 2 Device Type, I only have the choice between "None", "Retropad" or "Retropad /w analog"

**Comment by digitalLumberjack** [comment]
https://github.com/recalbox/recalbox-os/wiki/Play-from-3-to-4-players-to-SNES-%28EN%29

**Comment by Mojo4242** [comment]
nice thanks
