### ISSUE TITLE
Support for wifi driver MT7601

### ISSUE THREAD

**Issue by fmiyahira** [recalbox/recalbox-os#356]
Could you please add support for the wifi driver MT 7601 in the next version, the same problems as these issues #288 #335

**Comment by Fuhrmann** [comment]
:+1:, same here, please

**Comment by Frankan** [comment]
Help! Thanks!

**Comment by digitalLumberjack** [comment]
Hi, i'll take that seriously after the 3.3.0 beta release. The 3.3.0 beta release is planned before the end of the week :)

**Comment by fmiyahira** [comment]
Thanks for your feedback!

**Comment by Fuhrmann** [comment]
Nice! :)

Keep the good work guys.

**Comment by MiguelAngelLV** [comment]
Any progress? I use the last beta (3.3-beta5) and the doggle doesn't work

**Comment by MiguelAngelLV** [comment]
This [version support](http://groenholdt.net/Computers/RaspberryPi/MediaTek-MT7601-USB-WIFI-on-the-Raspberry-Pi/MediaTek-MT7601-USB-WIFI-on-the-Raspberry-Pi.html) kernels 3.19

**Comment by fooons** [comment]
I also have a Mediatek MT7601 Wifi dongle, and the way to solve the no wifi working in 4.0.0 is:

First of all we need the firmware for the MT7601 and copy it to the /lib/firmware. Because the filesystem is in read only mode we need to put it on rw mode to copy this firmware. Commands are as follow:

`mount -o remount,rw /`
`wget https://github.com/porjo/mt7601/raw/master/src/mcu/bin/MT7601.bin -O /lib/firmware/mt7601u.bin`
`reboot`

Thats all! and the adapter should work because firmware was missing. Next build I hope it will be included.

**Comment by rockaddicted** [comment]
Thanks, I'll look that ;)

**Comment by nadenislamarre** [comment]
https://github.com/porjo/mt7601
we have linux 4.1

and the last buidroot for rpi2 too :
https://github.com/buildroot/buildroot/blob/master/configs/raspberrypi2_defconfig

integrate the binary is not nice.
making the buildroot package takes time too.
Personnally, i would suggest at least a wiki.

**Comment by nadenislamarre** [comment]
done in 4.1

**Comment by Fuhrmann** [comment]
Good news! Thanks.
