### ISSUE TITLE
[ 3.3.0 beta17 ] PSX + N64: Black screen and return to Emulation Station

### ISSUE THREAD

**Issue by julianxhokaxhiu** [recalbox/recalbox-os#508]
Hi,

I would like to understand if I did something wrong on the installation and/or I missed some steps during the configuration. My current platform is Raspberry Pi 2.

Actually the only thing I changed is that the `/path/to/` is a mount via `samba` done every time at boot, and files are living in my NAS. This actually has totally no problem with `SNES`, `NES`, `GBC`, `GBA`, and even `Neo-Geo`.

PSX:
I'm trying to boot some Dumps from my original CDs did years ago as IMG, BIN, CUE and ISO but nothing of this is working. Logs:
```
['retroarch', '-L', '/usr/lib/libretro/pcsx_rearmed_libretro.so', '--config', '/recalbox/configs/retroarch/retroarchcustom.cfg', '/path/to/Crash Bandicoot 3 Warped/Crash Bandicoot 3.img']
Powering on HDMI with explicit settings (CEA mode 5)
Powering on HDMI with preferred settings
```
BIOS files are provided of course in the `/recalbox/share/bios` path.

N64:
Same situation, ROMs are provided as ZIP files.
```
['mupen64plus', '--corelib', '/usr/lib/libmupen64plus.so.2.0.0', '--gfx', '/usr/lib/mupen64plus/mupen64plus-video-gliden64.so', '--configdir', '/recalbox/configs/mupen64/', '--datadir', '/recalbox/configs/mupen64/', '/path/to/N64/Roms/Donkey Kong 64.zip']
Powering on HDMI with explicit settings (CEA mode 5)
Powering on HDMI with preferred settings
```
Tried with all three possible combinations: glide, n64 and mupen. They all behavior the same.

Any help is really appreciated. If I could provide any other log feel free to ask them.

Kind regards and thank you for this awesome micro-system really well packaged :) You rock!

**Comment by paradadf** [comment]
I figured out that all roms for n64 must be unzipped... That's the only way it worked for me.

**Comment by julianxhokaxhiu** [comment]
And what about PSX?

**Comment by paradadf** [comment]
Does it mean that the unzipped n64 roms worked for you? A feedback is always useful!
I only have .bin, .cue and .php files (also unzipped, as I they didn't work for me otherwise) and have no problem playing psx. Maybe your .img file (and others) have problems.

**Comment by julianxhokaxhiu** [comment]
No sorry I didn't try by unzipping them, I'll try that later. About PSX well I think they're fine because with any emulator on my PC it's working ( tested from Windows and Linux too ).

**Comment by julianxhokaxhiu** [comment]
@paradadf ok unzipped they work. So it's totally something missing with ZIP management maybe from the libretro porting of the emulator.

**Comment by paradadf** [comment]
Good to hear! Still, it would be better if zipped files work ;)

**Comment by rockaddicted** [comment]
N64 emulation is not provided by a libertro core, but the mupen64plus standalone version, which don't support .zip files. This extension will be removed for N64 ES/readme.

**Comment by julianxhokaxhiu** [comment]
@rockaddicted what about PSX? Any clue?

**Comment by rockaddicted** [comment]
PSX support zipped files, but retroarch uncompress each zipped game into `/share/extractions` before start it.
So that is not really a problem for snes rom of 4MB.
But if you do that with an ISO of 700MB or a PBP multidisc of 3GB... you'll have a blackscreen during a looooong time, and you will "broke" your SD card with these useless writes.
So about systems using cd image files, we recommend to use unzipped files. And we choosed to don't display .zip extension in ES about these systems.

**Comment by julianxhokaxhiu** [comment]
Well I can totally understand it, but it's not my case. As I explained before I'm loading PSX Roms through my NAS so there's no extraction/copy/etc.

On my case it seems more like a failure of "cannot open file" or something, but the file can be opened, persmissions are ok etc. Is there a way to get a detailed log somehow? I couldn't find anyone.

**Comment by rockaddicted** [comment]
Humm can you try to put PSX games directly on your sdcard and try to boot them ?
If they start without any problem once copied on your recalbox, the problem will come from your NAS/recalbox connection.

About N64, nope sorry, we are not using a libretro/retroarch core, and the N64 emulator used don't support zipped files.

**Comment by julianxhokaxhiu** [comment]
@rockaddicted tested and locally the same ISO file works! It seems to be an issue through Samba and the emulator. Can you please tell me how to get detailed log when for example, an emulator is not starting even if ES can see the game in the list?

**Comment by julianxhokaxhiu** [comment]
Found the issue: the roms path cannot contain a `#` character. I had just to remove that from a folder name and boom, now it works totally fine even from samba share :)

Thank you anyway for all the effort put on this!

**Comment by Neo-1986** [comment]
I have the same issue. I got a 32GB SD Card, everything works perfect. Now I bought a 128GB Samsung SD Card, everything works perfect, too, except the psx emulator. game seems to load but returns to frontend after 5-7sec.
i installed recalbox on the new sd card. Then, I copied the working folders roms, saves, bios from the 32gb SD Card to my computer and copied them back to the 128gb share folder.
This way, I did not have to scrape games again. And as I said, everything except psx works perfect, even mame or neogeo which are quite difficult to run because you need the correct mame/rom version.

The whole copying and copying back to the sd card took about 10-12 hours. So I don`t want to format my sd card again (by the way, it came with exfat, i formatted it to fat32). 

Has someone an idea what the cause of the problem could be?

the bios, saves, roms folders of the two sd cards are identical and both run 4.0.1 version of recalbox, even the background music and controllers are the same ;)

hope to hear from you soon. kind regards Neo
