### ISSUE TITLE
Create a new specific ES theme to recalbox

### ISSUE THREAD

**Issue by rockaddicted** [recalbox/recalbox-os#546]
Create a new specific custom theme respecting these making rules : 
- to use a unique background with a 1080p resolution
- to use svg offsets as system logos
- to include all existing systems on 3.3.0 + systems that should be added on 4.0.0 (amiga, atari ST, zx spectrum, viodeopack/odyssey 2, eightyone ZX81)
- to use opensource musics, normalized, encoded in OGG stereo, 44100 Hz, 160kps

**Comment by digitalLumberjack** [comment]
Yes that will be a great enhancement.
We need help on that.

**Comment by digitalLumberjack** [comment]
The theming system allows to place any svg in offset on top of the background. We can imagine using that for customizing each system, additionally to the logo.

**Comment by rockaddicted** [comment]
The list of systems to include in the 4.0.0 theme : 
```
amiga 600
amiga 1200
amstrad cpc
atari ST
atari2600
atari7800
cavestory
fba
fba_libretro
famicom disk system
gamegear
gb
gba
gbc
gw
imageviewer
lutro
lynx
mame
mastersystem
megadrive
moonlight
msx
n64
neogeo
nes
neogeo pocket
neogeo pocket color
Odyssey 2 / VideoPac 
pcengine
prboom (doom 1&2)
psx
scummvm
sega32x
segacd
sg1000
snes
vectrex
virtualboy
wonderswan
wonderswan color
ZX Spectrum
ZX81
```

**Comment by Dragda** [comment]
Have you been in consideration a big pictures theme like the Eudora-Bigshot? It has the same required parameters (single background, svg offsets, etc), has an clean aspect and the big scrapes looks really cool, especially in CTR monitors (looks great in any tv anyway).
I believe a lot of people will enjoy this type of theme. 
https://github.com/AmadhiX/es-theme-eudora-bigshot

**Comment by bigboo3000** [comment]
Hmmm I don't understand some choices:

1. Why separate amiga 600 et amiga 1200? There are very few games developped only for the 1200, the main difference is the enhanced chipset AGA with 256 colours.
I think it would be more simple to have only one Amiga entry, and in the theme it should be a picture of the Amiga 500 (the most succesful model by far)

2. More generally with more and more system added to recalbox It became difficult to navigate in emulation station. In the long term, to keep the interface lean, it would be better to keep enhanced version of a main hardware in the same entry (like it's already done with msx/msx2 or pcengine/pcengineCD for example) because they'll use the same emulator.

example:
nes+famicom disk system
gb+gbc
sg1000+mastersystem
megadrive+segacd (32x should be separated because genesis plus gx can't emulate it at the moment)
np+npc
worderswan+color
zx81+spectrum

**Comment by digitalLumberjack** [comment]
@bigboo3000 sadly we are not thinking the same. Having some b&w games beside of colored games in the same system is something i don't want. We have the possibility to get many systems now running at the same time, and we will split every systems we can.

Now what i see in your comment can just be done by puttin all the roms in one system :
nes+famicom disk system -> put all in nes
gb+gbc -> put all in gbc
sg1000+mastersystem -> put all in whatever
etc etc...
You will have what you want i we will have what we want :)

**Comment by bigboo3000** [comment]
Yep I will try that!  BUT to keep this logic you should separate msx1/2 and pcengine/pcengineCD because there are different hardware too.

**Comment by digitalLumberjack** [comment]
yes it is !
We will do that

**Comment by digitalLumberjack** [comment]
supergraphx too

**Comment by zarroun** [comment]
Hey guys, I'm a graphical artist from Switzerland and have been tinkering a little with ES themes lately, optimizing size for max quality n such. If you still need help with this, let me know. Wouldn't mind lending a hand to my favorite retro gaming station creator dudes!

**Comment by digitalLumberjack** [comment]
hi of course we are interested :)
We are currently creating a new theme http://blog.recalbox.com/forums/topic/new-theme-we-need-you/
If you want to help be sure we would be very happy :)

**Comment by zarroun** [comment]
Alrighty then, I'll pick a system not created yet and make a screen along the established style. Can't read everything, my french is not that great and google translate only goes so far :). You can assign me to the ZX Spectrum if you like. Got the perfect music for it too.

**Comment by digitalLumberjack** [comment]
Theme added in beta 3
