### ISSUE TITLE
[ 3.3.0 beta17 ] N64: Still black screen and return to Emulation Station 

### ISSUE THREAD

**Issue by mo64** [recalbox/recalbox-os#567]
Hi,

I still have the issue regarding the N64 emulator. 

I have an overclocked RPi 1. 

Tried several changes, e.g. in recalbox.conf, I tried all 3 core-modes; also changed the videomode to 640x480 resolution.

Also tried with changing the 4 to 2 in emulatorlauncher.sh.

But nothing works for me...

Can anybody help me please

BR mo64

**Comment by kryptto** [comment]
Mo64,

First off I am using a rpi2 overclocked.  I still have issues with N64 games displaying properly playing properly.  Understand that the split of compatible and properly working games is most likely 70/30.  I have games that run to black screens and maybe hear some sound otherwise inoperable.  

A suggestion, find another source and try downloading from there and try again...  

Maybe others have other things you can try.

Kryptto

**Comment by digitalLumberjack** [comment]
N64 emulator is not supported on recalbox rpi1.

**Comment by SpiralingOut** [comment]
N64 was previously working (with  a few tweaks) when I was running 3.2.11.  I recently upgraded to beta 17 and now N64 locks up usually after 5 mins or so of use.  I'm using and rpi2 and I've tried it overclocked and non-overclocked.  I've tried n64 plugin and glide plugin and both have the same issue.  Is there a fix for this?

**Comment by rockaddicted** [comment]
@kryptto : if you are using 3.3.0 beta 17, black screen must be a video mode problem. Look this wiki : https://github.com/recalbox/recalbox-os/wiki/N64-%3A-return-to-ES-%28EN%29
@SpiralingOut : about locks up issue, we'll continue in this issue https://github.com/recalbox/recalbox-os/issues/590
I close this one
