### ISSUE TITLE
HFS Partition not mounting.

### ISSUE THREAD

**Issue by mchtt** [recalbox/recalbox-os#597]
Is there any HFS support/drivers yet ? How to implement it ? Sorry if i did post in the wrong place.

**Comment by digitalLumberjack** [comment]
You are in the right place. We may not support HFS as it is really a non standard fs for an external drive. Why don't you use fat or ntfs ?

**Comment by julianxhokaxhiu** [comment]
Probably because he is a Mac user and NTFS is not coming by default ( or you have to pay for a decent driver ). FAT is an option but not for games that are bigger than 4G, although I know this is not the case for the emulators present in Recalbox :)

Anyway since it's a small driver I think would be anyway a nice addition.

**Comment by mchtt** [comment]
yes i'm a mac user, and i don't have a same size or bigger hdd to transfer my movies and change the fs :-(
will exFAT work ? (you can write >4GB and its compatible with Mac)

**Comment by nadenislamarre** [comment]
this is already enabled in the in developpment 4.0.0 version.

**Comment by mchtt** [comment]
yes ! :+1:
