### ISSUE TITLE
Ignored buttons mapped in kodi

### ISSUE THREAD

**Issue by askotx** [recalbox/recalbox-os#634]
I get a generic usb gamepad -snes like- on recalbox, but I can't use it well on kodi right and down keys are ignored.
version: **recalboxOS-v3.3.0-beta17**
Here is my input file on ~/.kodi/userdata/keymaps/recalbox.xml
`<joystick name="USB Gamepad ">`
`.. `
`<axis id="2" limit="-1">Up</axis> `
`<axis id="2" limit="-1">Down</axis>` 
`<axis id="1" limit="-1">Left</axis> `
`<axis id="1" limit="-1">Right</axis> `
`</joystick>`
Obviously Up and Down keys shares _Id="2"_ and _limit="-1"_ that's the reason is not responding well, but if I edit **recalbox.xml** when I enter to kodi it resets to default

**Comment by nadenislamarre** [comment]
fixed in the next release.
the file is regenerated when kodi starts depending on plugged devices so
you can fix easily.

**Comment by askotx** [comment]
How can I fix it in v3.3.0-beta17?

**Comment by nadenislamarre** [comment]
It requires the modification of a program.
So easyly you cannot.
However,
the problem is only with axes ; if your pad has a hat, you can use it.
If that's important for you, i suggest you to test our version 4.0.0 which
is stilll alpha, but already working well while we re on the last issues.
(you can come on our live irc to get more information)

Nicolas

2016-01-28 8:42 GMT+01:00 askotx <notifications@github.com>:

**Comment by askotx** [comment]
OK, a ps2 like controller works fine, so this can be avoided
