### ISSUE TITLE
add torrent app

### ISSUE THREAD

**Issue by stappern** [recalbox/recalbox-os#699]
Hi,
recalbox os is missing a torrent client (transmission runs great on raspberry 2) very useful in combination with Kodi,could you integrate it? its very hard to install when you dont have repository or ipkg

**Comment by digitalLumberjack** [comment]
Hi, no we won't add a torrent client.

**Comment by stappern** [comment]
why not? every other emulation/mediacenter for raspberry have it...(ora at
least you can easily install it)

Il giorno gio 18 feb 2016 alle ore 14:22 digitalLumberjack <
notifications@github.com> ha scritto:

**Comment by mchtt** [comment]
@stappern 
u should try OSMC/Retropie/Transmission combo.

**Comment by stappern** [comment]
i know very well the alternatives but recalbox is a great project and the
only thing missing is a torrent client ,until that day i'll have to dual
boot .....

Il giorno gio 18 feb 2016 alle ore 15:21 machette <notifications@github.com>
ha scritto:

**Comment by digitalLumberjack** [comment]
It's because recalbox is meant for retrogaming. The kodi media center is a wonderful thing, but is just an extra (that you can disable) in recalbox. I don't see recalbox as a media center, and never as a download center.

Second thing, it would be only CLI because we do not have a window manager. And if you are capable of using commandline interface to download a torrent, you can do it on you pc to place your downloaded files on a nas or nfs.

Third thing i don't want to add features I think is not in relation with retrogaming, or soon we will be an other raspbian :)

**Comment by stappern** [comment]
i get your poin,but transmission has a web interface so once installed you
can just forget it and manage from your mobile or any browser.you must
understand that most people have only 1 raspberry and wants to do
everything,so retrogaming,media center,download center.

you COULD insert an option to enable it like kodi(it can be off by default)
or at least insert ipkg/apt/yum/etc always as a plus so people can install
whatever they want.,i think having an option is always better.

Il giorno gio 18 feb 2016 alle ore 17:06 digitalLumberjack <
notifications@github.com> ha scritto:

**Comment by substring** [comment]
Dude, recalbox isn't a sum of rebranded apt-get/yum/ipkg/whichever packet manager

It's made from source code, like gentoo. The whole system is compiled from source code for the Pi. Adding a software means adding its source code to the system, and patch it when it won't work just from source. That's quite time consumming. So as you were told before, we won't add a torrent client because we don't want, and we dont have resources to waste on it.

Recalbox is open source, there are instructions.to compile it, you can give it a go and add transmission by yourself.

No offense here mate just respect digitalLumberjack's decision

**Comment by digitalLumberjack** [comment]
your arguments make sense @stappern but people that want to do everything with their raspberry will use raspbian/retropie

**Comment by stappern** [comment]
yea,its not the same,for the moment i'm booting a dual boot osmc/recalboxos
,its not great but its the fastest way to have torrent+recalbox

@subs  - no reason to be rude

Il giorno gio 18 feb 2016 alle ore 17:43 digitalLumberjack <
notifications@github.com> ha scritto:

**Comment by mchtt** [comment]
I'm running osmc and recalbox on seperate sd cards, not a big deal. and i'd rather prefer to have a gaming oriented os that only focus on gaming. 
If you try retropie, you will notice that it is not as plug'n play as recalbox, because the team is working on too many fronts.

**Comment by stappern** [comment]
yes i used retropie for a while but using 2 sdcards is not what i mean for
plug and play,especially if you use like me the raspberry under a tv and
you have a woman in the house :)

Il giorno ven 19 feb 2016 alle ore 10:55 machette <notifications@github.com>
ha scritto:

**Comment by mchtt** [comment]
same as you so no retrogaming until the girl is out :-P

**Comment by substring** [comment]
@mchtt @stappern guyz, you don't realize how lucky you are : the Pi has a very high WAF rate :) (Woman Appearance Factor)
