### ISSUE TITLE
[4.0.0] Extrem Over Clock bug and BG music not changed

### ISSUE THREAD

**Issue by showinfo** [recalbox/recalbox-os#754]
My profile 
RPI2 and recalbox 4.0.0 beta1

1. I changed over clock menu to "Extream Over clock". 
every time freezed at system boot on the way or system boot later in 1minutes. I think so some problem. 

2. I copied to MP3 file to /recalbox/share/music folder and reboot. But no changed bg music in emulationstation.  
I readed readme.txt in /recalbox/share/music folder
"Place your mp3 files here to replace default bg music in emulationstation"

**Comment by rockaddicted** [comment]
`Extrem overclock presset` is not really stable on all rpi2. On my rpi2 I've no problems since more 1 month, no freeze, perfect. But on some others rpi, there is freeze, so you must use an other preset. All rpi2 don't react of the same way with overclock, so you must try and adapt your preset to your hardware.

About the background musics in ES, I didn't try it. But if I understand, your mp3 files added in your  `/recalbox/share/music` folder are played ONLY if you are using a theme without any music integrated.
@digitalLumberjack will confirm / give more informations about this point.

**Comment by digitalLumberjack** [comment]
Yep each system with music will override the custom musics. The new theme contains no specific musics for themes, so all musics in this folder will be played.

**Comment by showinfo** [comment]
@digitalLumberjack How change bg music? or How to make new themes?

**Comment by rockaddicted** [comment]
please read es documentation : https://github.com/Aloshi/EmulationStation/blob/master/THEMES.md
and this issue : https://github.com/recalbox/recalbox-os/issues/546
If you need more support, use the forum :wink:
