### ISSUE TITLE
Recalbox manager app

### ISSUE THREAD

**Issue by adolfobenjaminv** [recalbox/recalbox-os#851]
This is my idea:
An app similar to the manager site that let you manage your roms, bios, etc directly from your android/iphone.
Maybe a free version and a premium version without adds.
Also, could be great if it had direct access to the wiki, and the irc channel :D
Just an idea

**Comment by Laddyacris** [comment]
Like Recalbox-Manager ? https://github.com/recalbox/recalbox-manager
https://github.com/recalbox/recalbox-os/wiki/recalbox-manager-WEB-interface-%28FR%29

**Comment by adolfobenjaminv** [comment]
Exactly!

**Comment by MikaXII** [comment]
Good idea but we already do it^^.
We haven't mobile apps but if some people want control recalbox they can use the restfull api to make an app on android/IOS/WP

**Comment by adolfobenjaminv** [comment]
i know, the web interface is cool so an app would be amazing :D

**Comment by MikaXII** [comment]
I agree with you, but making an app for android / IOS isn't our priority because the manager web work fine.
If some people want release a mobile app he can do this easely with neolao's project : [recalbox-api](https://github.com/neolao/recalbox-api)

**Comment by substring** [comment]
errrr ... why don't you add a favourite on your phone pointing to the manager ? works the same :dancer:

**Comment by MikaXII** [comment]
Because native apps better than webapps :smile: :trollface:

**Comment by nadenislamarre** [comment]
better ?
Native apps require a minimum of 3 codings apps or to pay such xamarin
framework, and to pay to be on the market.

The existing webapp works for any hardware, including computers, phones,
tablet and is not subject to be remade from scratch in case the framework
redesign.

Ui experience is neigher better on native apps for management applications
like this one.

Recalbox is based on open, free, extensible and robust softwares.
So, anybody who write a such application is welcome, but dont expect to get
this from the current team members i think, because our tasks list is huge
; personnally, i see no advantage at all (please give me yours).

Note that for kodi, such applications already exists.
It's just for the roms management that it could be done. Note that
downloading and extract a rom on a phone is already a nightmare -- when the
website works on phones or have not too much ads to hide buttons.

BUT
PLEASE proove me i'm wrong by writting a such application ;-)

**Comment by MikaXII** [comment]
Faster, better ui ?
Haha please @nadenislamarre I'm trolling ; )
I think both are useful in a specific context.

**Comment by rockaddicted** [comment]
The recalbox team won't work on a native apps.
So I close this issue.
But, if someone want to work on this feature, using the [recalbox-api](https://github.com/neolao/recalbox-api), we'll reopen it.
