### ISSUE TITLE
Wifi password in plain text

### ISSUE THREAD

**Issue by Taciturn0** [recalbox/recalbox-os#853]
Recalbox 4.0.0 beta 2
Need more security hidding Wifi password. Anyone who use your recalbox can see your wifi password in the settings. Also you can see it in plain text in the log files. This can be fix in the next update?

**Comment by nadenislamarre** [comment]
This is in my todolist together with some other security things, but not
for the next update.
You can for the moment disable services such as ssh, samba, web interface
to avoid accesses.

Nicolas

**Comment by nadenislamarre** [comment]
in 4.1 i removed 1 occurrence of the log files.

Which log files have you seen please ?
About the configuration file, it is required to keep in mind the wifi password to be able to connect.
Which suggestion do you have to make it better ?

**Comment by substring** [comment]
@nadenislamarre 
what about http://www.slightlydave.co.uk/Main/wpa_supplicant-psk-generator-hide-that-password/ to store a hidden password ?

**Comment by nadenislamarre** [comment]
"As you can see, the psk is a little less readable than the original psk"

yes, we can do that or encode simplyly in base64 more simplyly in
recalbox.conf,
personnally, i don't like it because, it makes people think it's secure
while it's not, while a simple copy and past to any decoder url and the
password is decrypt.. (https://www.base64decode.org/)

Example, try to get my password if you have access to my recalbox.conf that
my password is : dG90bw== encoded in base64


=> I will do something like this to get something acceptable :

1) force people to change the ssh password...

2)
One way to secure would be to add an information that is not available from
samba / web manager,
for example,

encode in base 64 :
pi unique card member + ethernet mac address + wifi
so that it needs these information to be decoded (so, not base64 in fact,
but more des algorithm)

so that a ssh connection is required to decode the password.
we must be sure that these informations are only available via ssh.

When the wifi password is read, if it starts by a key word, let it, other
wise, rewrite it automatically in the encoded way.

**Comment by substring** [comment]
nothing is secure on a recalbox, you just log in as root ! it doesn't hold any private data ! The point of the issue is just "don't leave a plain text password in a file". The link i suggested is just perfect for that. Think about the support script ...

Anyway cracking a wifi password is as _easy as killing babies with axes_ (duke nukem quote ^^), so talking about security about a wifi password is a non sense almost ;) Just not in plain text ;)

**Comment by Taciturn0** [comment]
Hey I want to thank you for working with the security in the app. I know that if you use Recalbox just for gaming people dont add any peronal data but using Kodi is another story because many people add share folders in other computers to access their media and other things. I am just a common user and I dont understand a lot of how to fix this but I find this article that may or may not help. 
Thank you again.
http://www.slashroot.in/how-are-passwords-stored-linux-understanding-hashing-shadow-utils

**Comment by nadenislamarre** [comment]
Don't worry, i'm working on the subject.
Just wait and see my next pr.
