### ISSUE TITLE
[Feature Request] Option to disable metadata save on exit

### ISSUE THREAD

**Issue by torra87** [recalbox/recalbox-os#918]
To achieve the best performance on exit/reboot, it would be awesome to have an option to disable the metadata save. 
If recalbox have a .config option please tell me the name because i couldn't find any.
Retropie has this option: https://github.com/retropie/retropie-setup/wiki/FAQ#why-does-shut-down-and-reboot-take-ages

Thanks!

**Comment by Duglim** [comment]
Wouldn't you loose all new metadata since last saving in this case?
I would propose to:
- Only build/save the metadata on exit, if there has been a change since last saving process.
- Only build/save the metadata of the system which had changes since past saving process.

Greetings, Dan

**Comment by Atmosfear1968** [comment]
I would more than happy if the metadata would NOT be saved on Exit/Reboot. I have 10000+ Roms on my NAS and even on my Gigabit Network with around 80-90mb/s, it took nearly a half hour to reboot !
A Option in the System Menu to disable the Metadata save would be nice. Scrape i do always on the PC because its alot faster.

Thanks

**Comment by torra87** [comment]
I have the same scenario as @Atmosfear1968

**Comment by Atmosfear1968** [comment]
I forgot to mention, there may be also another problem beside of performance problem. I have 3 rpi´s in my house for the kids. What happens if 2 of them do a reboot at the same time ? or i did update the metadata on the pc and forgot to switch of one of the rpi`s ? Those rpi will alter the updated Metadata on the NAS back to its old stage on Exit/Reboot ?

**Comment by paradadf** [comment]
I'm not sure if this is the right place, but just saw a fix for long exit times while saving metadatas on RetroPie that might be interesting to look into.
https://github.com/RetroPie/EmulationStation/pull/65

**Comment by torra87** [comment]
I'm using Fast Shutdown already, so this request can be closed.
Thanks!

**Comment by digitalLumberjack** [comment]
great i close
