### ISSUE TITLE
Images failing to display when using Mac to Scrape Games.

### ISSUE THREAD

**Issue by kryptalivian** [recalbox/recalbox-os#928]
Made changes to Mac portion of PC scrapping Wiki. Command kept failing until i typed ./ in front of scraper. 

I scraped all my consoles and used the code that points the image to the correct folder, but I found it only displays the info on the game but not the image. 

First I thought its because I put it on a flash drive, but then I put the files locally on my Pi. I also tried updating the list from Emulation Station Menu.

**Comment by daaa57150** [comment]
Must be because the paths to your images are wrong in gamelist.xml

This is how I did it:
On my mac I have a folder structure like this (I mimic the structure from the recalbox):
```
+snes
    +downloaded_images
    -gamelist.xml
    -rom1
    -rom2
+megadrive
+segacd
+gba
-scraper
```

This is the command I launch for snes (you 1st need to cd to the dir with the scraper):
`./scraper -rom_dir=snes -image_dir=./snes/downloaded_images -no_thumb=true -max_width=400 -output_file=snes/gamelist.xml -image_path=/recalbox/share/roms -gdb_img=b -use_ovgdb=true -rom_path=/recalbox/share/roms/snes`

Then copy everything on your recalbox and it should work.
It's the same for the other systems, just replace snes by the name of the other systems' names

**Comment by kryptalivian** [comment]
I'll take a look at that, thanks!

**Comment by substring** [comment]
People using Mac or Linux should know that it's always better to add ./ in front of a binary. As this is no real issue, i'm closing it :) Edit the wiki accordingly if necessary :)
